name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Python Wheel
      run: pip install wheel
    - name: Install PlatformIO Core
      run: pip install -U platformio
    - name: Copy generic config over
      run: cp myConfig.example.h myConfig.h
    - name: Copy F412ZG variant files
      run: |
        cp f412zg_variant_files/nucleo_f412zg.json ~/.platformio/platforms/ststm32/boards/nucleo_f412zg.json
        cp f412zg_variant_files/ldscript.ld ~/.platformio/packages/framework-arduinoststm32/variants/STM32F4xx/F412Z(E-G)(J-T)/ldscript.ld
        cp f412zg_variant_files/variant_NUCLEO_F412ZG.h ~/.platformio/packages/framework-arduinoststm32/variants/STM32F4xx/F412Z(E-G)(J-T)/variant_NUCLEO_F412ZG.h
        cp f412zg_variant_files/variant_NUCLEO_F412ZG.cpp ~/.platformio/packages/framework-arduinoststm32/variants/STM32F4xx/F412Z(E-G)(J-T)/variant_NUCLEO_F412ZG.cpp
    - name: Compile EX-IOExpander (all default platforms)
      run: python -m platformio run
